netlist: Fix test issue with guile-2.0 (rename a module).
When building with guile-2.0, the procedure sort() conflicts with the module
name '(netlist sort)' with the error as follows:

ERROR: In procedure #<directory (netlist sort) 23163f0>:
ERROR: Wrong type to apply: #<directory (netlist sort) 23163f0>

Since the module (netlist sort) is, generally, not about sorting,
it has been renamed to avoid the conflict (instead of using of
another sort function).  Other procedures (especially those
working with duplicates, e.g., from symcheck code base) can go
there in future.